### PR TITLE
added stenography.py 

### PR DESCRIPTION
**Pull request by voidninjaaa-panda**
hide text inside a image python code

### CODE REVIEW

**Comment by yash-gulatii** [comment]
There is a bug. I am not able decode the image encode by this program. Please fix this bug. And if this is not a bug please give proper documentation/steps to run the program. Thanks btw Amazing Project!!

**Comment by voidninjaaa-panda** [comment]
pip install tk 
pip install Pillow
this library are need to be installed then it works fine
image

**Comment by voidninjaaa-panda** [comment]
it works decoded a encoded image 
encoded image
image
decoded image
image
more info 
image

**Comment by yash-gulatii** [comment]
Please remove the file from the main directory.

**Comment by voidninjaaa-panda** [comment]
Done

**Comment by yash-gulatii** [comment]
Great Work @voidninjaaa-panda. also You have great designing skills. Your App looks so professional.

**Comment by voidninjaaa-panda** [comment]
it showing excluded on hacktoberfest  website

**Comment by yash-gulatii** [comment]
Yeah it is i don't why it is.

**Comment by voidninjaaa-panda** [comment]
is their any solution for it

**Comment by yash-gulatii** [comment]
I have created another repository https://github.com/yash-gulatii/Open-Source_Projects. Here you can contribute.

**Pull request merged**
