### PR TITLE
Create Selfies_with_Python.py

### PR DESCRIPTION
**Pull request by MrB141107**
A Python Program for the users to take selfies using the OpenCV module, users must install `opencv-python` or `opencv-contrib-python`.

### CODE REVIEW

**Comment by yash-gulatii** [comment]
Please give appropriate documentation to use the program as i was unable to use it. A window opened then the program was stuck and nothing happend.

**Comment by MrB141107** [comment]
@yash-gulatii
# Pull Request: Selfie with Python

## Description
A Python Program for the users to take selfies using the OpenCV module.

## Changes Made
- Added a Python script for taking pictures.
- Added user-friendly input and output prompts.

## Requirements 
- Install the `opencv-contrib-python` module only.
- `Integrated camera` or `External webcam`.

## Usage
- Run the script and camera prompt will appear.
- Hit `space-bar` to click pictures.
- Hit `escape-key` to terminate the window.

**Comment by yash-gulatii** [comment]
Amazing Project @MrB141107 !
Thanks for the Cotribution.

**Comment by MrB141107** [comment]
@yash-gulatii, I am sad to inform you that your repository has been excluded by the Hacktoberfest authorities.
image

**Comment by yash-gulatii** [comment]
Yeah I know But sorry. Is there anything i did wrong??

**Comment by MrB141107** [comment]
Yeah @yash-gulatii, I do know the reason...
Hacktoberfest is a competition for open-source contributions to any project based on Github, if any user keeps the repo name which includes the word `hacktoberfest`, that means that the  is just created for hacktoberfest competition, not for any open-source contributions so the authorities of hacktoberfest, clearly exclude the repositories named on `hacktoberfest`

They just include the repositories, which seems to have a name like a project, although it is made just for hacktoberfest purpose. As you can see my repository, which is made for hacktoerfest but the name suggest as `Python_Projects`

I got to know this reason because my repo got excluded last year, so I contacted the authorites, and they informed me.

**Comment by MrB141107** [comment]
Still, you have a lot of time remaining, I suggest you to create a new repo, without na ame including `hacktoberfest` word. Wish you all the best

**Comment by yash-gulatii** [comment]
Ohh Thanks @MrB141107 !! I am creating one.

**Pull request merged**
